# Cleaning Data

In [2]:
import pandas as pd

In [19]:
df = pd.read_excel("Datasets/signup.xlsx")
df

     name   age        email signup_date
0   Alice  29.0  a@gmail.com  2024-01-02
1     Bob   NaN  b@gmail.com  2024-01-03
2  Carlos  41.0          NaN  2024-01-05
3     NaN  35.0          NaN  2024-01-06
4     NaN   NaN          NaN         NaT
5    John  21.0  j@gmail.com  2024-01-08
6   Alice  29.0  a@gmail.com  2024-01-02
7  Carlos  41.0          NaN  2024-01-05

<h2 style = "color:#4fd4ff" >Detecting Missing Values</h2>

Before you can fix missing data, you need to find it. <br>
Pandas represents a missing value as NaN (Not a Number). <br>
isnan() returns a same-shaped DataFrame of True/False. <br>
Returns True whenever a cell is missing.

In [5]:
df.isna()

    name    age  email  signup_date
0  False  False  False        False
1  False   True  False         True
2  False  False   True        False
3   True  False   True        False

Knowing that missing values exist is step 1. <br>
Knowing exactly how many, and in which columns, is what turns that into a plan. <br>
Chaining .sum() onto .isna() returns the count of missing values in each column.

In [17]:
df.isna().sum()

name           1
age            1
email          2
signup_date    1
dtype: int64

In [18]:
(df.isna().sum()/len(df) * 100).sort_values(ascending = False) # Percentage missing per column

email          50.0
name           25.0
age            25.0
signup_date    25.0
dtype: float64

In [21]:
df.isna().sum().sum() # Total missing cells in the entire DataFrame

np.int64(5)

In [22]:
df.info() # shows non-null count per column which is a mirror image of this command df.isna().sum()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         3 non-null      str
 1   age          3 non-null      float64
 2   email        2 non-null      str
 3   signup_date  3 non-null      datetime64[us]
dtypes: datetime64[us](1), float64(1), str(2)
memory usage: 260.0 bytes

<h2 style = "color:#4fd4ff" >Dropping Rows or Columns - dropna()</h2>

In [23]:
df.dropna() # Drops any row with at least one missing value

    name   age        email signup_date
0  Alice  29.0  a@gmail.com  2024-01-02

In [8]:
df.dropna(axis = 1) # Drops any column with a missing value instead of rows

  signup_date
0  2024-01-02
1  2024-01-03
2  2024-01-05
3  2024-01-06

In [13]:
df.dropna(how = "all") # Only drops a row if all its values are missing

     name   age        email signup_date
0   Alice  29.0  a@gmail.com  2024-01-02
1     Bob   NaN  b@gmail.com  2024-01-03
2  Carlos  41.0          NaN  2024-01-05
3     NaN  35.0          NaN  2024-01-06
5    John  21.0  j@gmail.com  2024-01-08

In [18]:
df.dropna(subset = ["name", "email"]) # Only considers missing values in specific columns

    name   age        email signup_date
0  Alice  29.0  a@gmail.com  2024-01-02
1    Bob   NaN  b@gmail.com  2024-01-03
5   John  21.0  j@gmail.com  2024-01-08

<h2 style = "color:#4fd4ff" >Duplicate Rows</h2>

Data collected from multiple sources - for example a form resumbited, 2 systems  merged, a scrapper run twice, almost always produces duplicate rows.<br>
.duplicated() flags them <br>
.drop_duplicates() removes them

In [29]:
df = pd.read_excel("Datasets/kids_records.xlsx")
df

,student_id,first_name,last_name,gender,age,grade,email,phone_number,enrollment_date,gpa,city,guardian_name,attendance_rate
0,STU00781,Shawn,Jacobson,Female,10.0,Grade 7,NaN,+260-95-4635470,18/09/2019,3.76,chipata,Tamara Jacobson,99.9
1,STU00101,Joseph,Osborne,FEMALE,9.0,Grade 8,joseph.osborne408@outlook.com,+260-97-9237735,16/06/2024,1.84,Solwezi,Amber Osborne,81.8
2,STU00168,Ryan,Bell,female,16.0,Grade 1,ryan.bell226@school.edu.zm,0975948917,08-14-2019,3.74,kabwe,Brandon Bell,60.2
3,STU01631,Bruce,Cannon,male,12.0,Grade 1,brucec79@school.edu.zm,0966619976,2018-02-15,1.88,kabwe,Justin Cannon,97.8
4,STU01711,Jeremy,Reid,Male,11.0,Grade 7,jeremy_reid@school.edu.zm,+260-95-9005240,2018-08-24,3.15,Mongu,Madison Reid,74.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5063,STU03458,Kathleen,Hayden,NaN,9.0,Grade 2,kathleen.hayden680@yahoo.com,(96) 7948103,2024-03-14,1.72,CHINGOLA,Marcus Hayden,74.9
5064,STU01769,Jeremy,Cardenas,F,10.0,Grade 10,jeremy_cardenas@school.edu.zm,+260-97-4674007,2018/03/17,2.47,Chipata,Amanda Cardenas,80.3
5065,STU01738,Bridget,Mcneil,M,14.0,Grade 4,amy.chapman801@outlook.com,260961601308,11-24-2020,3.96,chipata,Stephanie Mcneil,97.8
5066,STU03241,Donald,Simmons,F,999.0,Grade 9,donald.simmons77@school.edu.zm,+260-96-3500233,2020-10-17,3.02,Ndola,Sherry Simmons,NaN
5067,STU04738,Melissa,Dixon,Male,13.0,Grade 7,melissa_dixon@outlook.com,(95) 1489097,02/03/2023,3.64,mansa,George Dixon,85.5

In [27]:
df.isna().sum()

student_id           8
first_name          58
last_name           58
gender             160
age                211
grade              110
email              262
phone_number       309
enrollment_date    162
gpa                260
city               210
guardian_name      160
attendance_rate    214
dtype: int64

In [26]:
(df.isna().sum()/len(df) * 100).sort_values(ascending = False)

phone_number       6.097080
email              5.169692
gpa                5.130229
attendance_rate    4.222573
age                4.163378
city               4.143646
enrollment_date    3.196527
guardian_name      3.157064
gender             3.157064
grade              2.170481
last_name          1.144436
first_name         1.144436
student_id         0.157853
dtype: float64

In [31]:
df.dropna(how = "all")

,student_id,first_name,last_name,gender,age,grade,email,phone_number,enrollment_date,gpa,city,guardian_name,attendance_rate
0,STU00781,Shawn,Jacobson,Female,10.0,Grade 7,NaN,+260-95-4635470,18/09/2019,3.76,chipata,Tamara Jacobson,99.9
1,STU00101,Joseph,Osborne,FEMALE,9.0,Grade 8,joseph.osborne408@outlook.com,+260-97-9237735,16/06/2024,1.84,Solwezi,Amber Osborne,81.8
2,STU00168,Ryan,Bell,female,16.0,Grade 1,ryan.bell226@school.edu.zm,0975948917,08-14-2019,3.74,kabwe,Brandon Bell,60.2
3,STU01631,Bruce,Cannon,male,12.0,Grade 1,brucec79@school.edu.zm,0966619976,2018-02-15,1.88,kabwe,Justin Cannon,97.8
4,STU01711,Jeremy,Reid,Male,11.0,Grade 7,jeremy_reid@school.edu.zm,+260-95-9005240,2018-08-24,3.15,Mongu,Madison Reid,74.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5063,STU03458,Kathleen,Hayden,NaN,9.0,Grade 2,kathleen.hayden680@yahoo.com,(96) 7948103,2024-03-14,1.72,CHINGOLA,Marcus Hayden,74.9
5064,STU01769,Jeremy,Cardenas,F,10.0,Grade 10,jeremy_cardenas@school.edu.zm,+260-97-4674007,2018/03/17,2.47,Chipata,Amanda Cardenas,80.3
5065,STU01738,Bridget,Mcneil,M,14.0,Grade 4,amy.chapman801@outlook.com,260961601308,11-24-2020,3.96,chipata,Stephanie Mcneil,97.8
5066,STU03241,Donald,Simmons,F,999.0,Grade 9,donald.simmons77@school.edu.zm,+260-96-3500233,2020-10-17,3.02,Ndola,Sherry Simmons,NaN
5067,STU04738,Melissa,Dixon,Male,13.0,Grade 7,melissa_dixon@outlook.com,(95) 1489097,02/03/2023,3.64,mansa,George Dixon,85.5

In [32]:
df.dropna(subset = ["student_id"])

,student_id,first_name,last_name,gender,age,grade,email,phone_number,enrollment_date,gpa,city,guardian_name,attendance_rate
0,STU00781,Shawn,Jacobson,Female,10.0,Grade 7,NaN,+260-95-4635470,18/09/2019,3.76,chipata,Tamara Jacobson,99.9
1,STU00101,Joseph,Osborne,FEMALE,9.0,Grade 8,joseph.osborne408@outlook.com,+260-97-9237735,16/06/2024,1.84,Solwezi,Amber Osborne,81.8
2,STU00168,Ryan,Bell,female,16.0,Grade 1,ryan.bell226@school.edu.zm,0975948917,08-14-2019,3.74,kabwe,Brandon Bell,60.2
3,STU01631,Bruce,Cannon,male,12.0,Grade 1,brucec79@school.edu.zm,0966619976,2018-02-15,1.88,kabwe,Justin Cannon,97.8
4,STU01711,Jeremy,Reid,Male,11.0,Grade 7,jeremy_reid@school.edu.zm,+260-95-9005240,2018-08-24,3.15,Mongu,Madison Reid,74.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5063,STU03458,Kathleen,Hayden,NaN,9.0,Grade 2,kathleen.hayden680@yahoo.com,(96) 7948103,2024-03-14,1.72,CHINGOLA,Marcus Hayden,74.9
5064,STU01769,Jeremy,Cardenas,F,10.0,Grade 10,jeremy_cardenas@school.edu.zm,+260-97-4674007,2018/03/17,2.47,Chipata,Amanda Cardenas,80.3
5065,STU01738,Bridget,Mcneil,M,14.0,Grade 4,amy.chapman801@outlook.com,260961601308,11-24-2020,3.96,chipata,Stephanie Mcneil,97.8
5066,STU03241,Donald,Simmons,F,999.0,Grade 9,donald.simmons77@school.edu.zm,+260-96-3500233,2020-10-17,3.02,Ndola,Sherry Simmons,NaN
5067,STU04738,Melissa,Dixon,Male,13.0,Grade 7,melissa_dixon@outlook.com,(95) 1489097,02/03/2023,3.64,mansa,George Dixon,85.5

In [33]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
5063    False
5064    False
5065    False
5066    False
5067    False
Length: 5068, dtype: bool