# Transforming Data

<h2 style = "color:#4fd4ff" >Creating New Columns From Existing Ones</h2>

The simplest transformation is arithmetic between existing columns. <br> 
Assign to a new column name with square-bracket notation, and pandas computes the whole column in one vectorized pass, no loop required.

In [1]:
import pandas as pd

In [11]:
data = {
    "name" : ["Alice", "Bob", "Diana", "Carlos"],
    "revenue" : [1200, 950, 1800, 700],
    "cost" : [800, 700, 1100, 650]
}

df = pd.DataFrame(data)

df["Profit"] = df["revenue"] - df["cost"]

df["Double Cost"] = df["cost"] * 2

df["Margin Percent"] = df["Profit"] / df["revenue"] * 100

df["Is Profitable"] = df["Profit"] > 0

df

     name  revenue  cost  Profit  Double Cost  Margin Percent  Is Profitable
0   Alice     1200   800     400         1600       33.333333           True
1     Bob      950   700     250         1400       26.315789           True
2   Diana     1800  1100     700         2200       38.888889           True
3  Carlos      700   650      50         1300        7.142857           True

<h2 style = "color:#4fd4ff" >.apply() - Applying any functions to rows or columns</h2>

When a transformation can't be expressed as simple arithmetic, .apply() is the most flexible tool: <br> 
it runs any Python function over every column, or with axis=1 — over every row.

In [7]:
data = {
    "name" : ["Alice", "Bob", "Diana", "Carlos"],
    "score" : [60, 55, 92, 85],
    "city" : ["London", "Berlin", "Paris", "Rome"]
}

students_df = pd.DataFrame(data)

def grade(score):
    if score >= 90:
        return "A+"
    elif score >= 85:
        return "A"
    elif score >= 70:
        return "B"
    elif score >= 60:
        return "C"
    elif score >= 50:
        return "D"
    else:
        return "F"

def summary(row):
    return f"{row['name']} scored {row['score']} and obtained {row['grade']}"

students_df["grade"] = students_df["score"].apply(grade)

students_df["summary"] = students_df.apply(summary, axis = 1)

students_df

     name  score    city grade                          summary
0   Alice     60  London     C   Alice scored 60 and obtained C
1     Bob     55  Berlin     D     Bob scored 55 and obtained D
2   Diana     92   Paris    A+  Diana scored 92 and obtained A+
3  Carlos     85    Rome     A  Carlos scored 85 and obtained A

<h2 style = "color:#4fd4ff" >.map() - Element-wise transformation on a Series</h2>

**.map()** is Series-only, and it's built for exactly one job: <br>
transforming every value in a column, one at a time. <br>
It accepts either a function or a dictionary lookup, and the dictionary form is especially clean for recoding categories.

In [10]:
students_df["city_upper"] = students_df["city"].map(lambda c : c.upper())
country_of = {
    "London" : "UK",
    "Berlin" : "DE",
    "Paris" : "FR",
    "Rome" : "IT"
}

students_df["country"] = students_df["city"].map(country_of)

students_df

,name,score,city,grade,summary,city_upper,country
0,Alice,60,London,C,Alice scored 60 and obtained C,LONDON,UK
1,Bob,55,Berlin,D,Bob scored 55 and obtained D,BERLIN,DE
2,Diana,92,Paris,A+,Diana scored 92 and obtained A+,PARIS,FR
3,Carlos,85,Rome,A,Carlos scored 85 and obtained A,ROME,IT

<h2 style = "color:#4fd4ff" >.assign() - Adding multiple columns at once</h2>

In [15]:
data = {
    "name" : ["Alice", "Bob", "Diana", "Carlos"],
    "revenue" : [1200, 950, 1800, 700],
    "cost" : [800, 700, 1100, 650]
}

df2 = pd.DataFrame(data)
df2 = df2.assign(
    profit = df2.revenue - df2.cost,
    dcost = df2.cost * 2,
    percent = lambda x : x.profit / df2.revenue * 100,
    isprofit = lambda x : x.profit > 0
)

df2

     name  revenue  cost  profit  dcost    percent  isprofit
0   Alice     1200   800     400   1600  33.333333      True
1     Bob      950   700     250   1400  26.315789      True
2   Diana     1800  1100     700   2200  38.888889      True
3  Carlos      700   650      50   1300   7.142857      True