# Cleaning Data

In [2]:
import pandas as pd
import numpy as np
from openpyxl.styles import PatternFill

In [2]:
df = pd.read_excel("Datasets/signup.xlsx")
df

     name   age        email signup_date
0   Alice  29.0  a@gmail.com  2024-01-02
1     Bob   NaN  b@gmail.com  2024-01-03
2  Carlos  41.0          NaN  2024-01-05
3     NaN  35.0  b@gmail.com  2024-01-06
4     NaN   NaN          NaN         NaT
5    John  21.0  j@gmail.com  2024-01-08
6   Alice  29.0  a@gmail.com  2024-01-02
7  Carlos  41.0          NaN  2024-01-05

<h2 style = "color:#4fd4ff" >Detecting Missing Values</h2>

Before you can fix missing data, you need to find it. <br>
Pandas represents a missing value as NaN (Not a Number). <br>
isnan() returns a same-shaped DataFrame of True/False. <br>
Returns True whenever a cell is missing.

In [5]:
df.isna()

    name    age  email  signup_date
0  False  False  False        False
1  False   True  False         True
2  False  False   True        False
3   True  False   True        False

Knowing that missing values exist is step 1. <br>
Knowing exactly how many, and in which columns, is what turns that into a plan. <br>
Chaining .sum() onto .isna() returns the count of missing values in each column.

In [17]:
df.isna().sum()

name           1
age            1
email          2
signup_date    1
dtype: int64

In [18]:
(df.isna().sum()/len(df) * 100).sort_values(ascending = False) # Percentage missing per column

email          50.0
name           25.0
age            25.0
signup_date    25.0
dtype: float64

In [21]:
df.isna().sum().sum() # Total missing cells in the entire DataFrame

np.int64(5)

In [22]:
df.info() # shows non-null count per column which is a mirror image of this command df.isna().sum()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         3 non-null      str
 1   age          3 non-null      float64
 2   email        2 non-null      str
 3   signup_date  3 non-null      datetime64[us]
dtypes: datetime64[us](1), float64(1), str(2)
memory usage: 260.0 bytes

<h2 style = "color:#4fd4ff" >Dropping Rows or Columns - dropna()</h2>

In [23]:
df.dropna() # Drops any row with at least one missing value

    name   age        email signup_date
0  Alice  29.0  a@gmail.com  2024-01-02

In [8]:
df.dropna(axis = 1) # Drops any column with a missing value instead of rows

  signup_date
0  2024-01-02
1  2024-01-03
2  2024-01-05
3  2024-01-06

In [13]:
df.dropna(how = "all") # Only drops a row if all its values are missing

     name   age        email signup_date
0   Alice  29.0  a@gmail.com  2024-01-02
1     Bob   NaN  b@gmail.com  2024-01-03
2  Carlos  41.0          NaN  2024-01-05
3     NaN  35.0          NaN  2024-01-06
5    John  21.0  j@gmail.com  2024-01-08

In [18]:
df.dropna(subset = ["name", "email"]) # Only considers missing values in specific columns

    name   age        email signup_date
0  Alice  29.0  a@gmail.com  2024-01-02
1    Bob   NaN  b@gmail.com  2024-01-03
5   John  21.0  j@gmail.com  2024-01-08

<h2 style = "color:#4fd4ff" >Duplicate Rows</h2>

Data collected from multiple sources - for example a form resumbited, 2 systems  merged, a scrapper run twice, almost always produces duplicate rows.<br>
.duplicated() flags them <br>
.drop_duplicates() removes them

In [5]:
#df = pd.read_excel("Datasets/kids_records.xlsx")
#df

In [11]:
df.isna().sum()

name           2
age            2
email          4
signup_date    1
dtype: int64

In [12]:
(df.isna().sum()/len(df) * 100).sort_values(ascending = False)

email          50.0
name           25.0
age            25.0
signup_date    12.5
dtype: float64

In [26]:
df = df.dropna(how = "all")

In [15]:
df.dropna(subset = ["name"])

     name   age        email signup_date
0   Alice  29.0  a@gmail.com  2024-01-02
1     Bob   NaN  b@gmail.com  2024-01-03
2  Carlos  41.0          NaN  2024-01-05
5    John  21.0  j@gmail.com  2024-01-08
6   Alice  29.0  a@gmail.com  2024-01-02
7  Carlos  41.0          NaN  2024-01-05

In [22]:
df.duplicated().sum()

np.int64(2)

In [23]:
df.drop_duplicates()

     name   age        email signup_date
0   Alice  29.0  a@gmail.com  2024-01-02
1     Bob   NaN  b@gmail.com  2024-01-03
2  Carlos  41.0          NaN  2024-01-05
3     NaN  35.0  b@gmail.com  2024-01-06
4     NaN   NaN          NaN         NaT
5    John  21.0  j@gmail.com  2024-01-08

In [29]:
dup_emails = df[df.duplicated(subset = ["email"], keep = False)].sort_values("email")
print(dup_emails)

     name   age        email signup_date
0   Alice  29.0  a@gmail.com  2024-01-02
6   Alice  29.0  a@gmail.com  2024-01-02
1     Bob   NaN  b@gmail.com  2024-01-03
3     NaN  35.0  b@gmail.com  2024-01-06
2  Carlos  41.0          NaN  2024-01-05
7  Carlos  41.0          NaN  2024-01-05

In [3]:
students_df = pd.read_excel("Datasets/school_kids_100.xlsx")

In [15]:
students_df = students_df.dropna(how = "all")

students_df.duplicated().sum()

students_df = students_df.drop_duplicates()

students_df.duplicated().sum()

students_df = students_df.dropna(subset = ["student_id"])
students_df

print(len(students_df))

students_df["gender"] = students_df["gender"].str.strip().str.upper().map({
    "m" : "Male",
    "M" : "Male",
    "MALE" : "Male",
    "male" : "Male",
    "female" : "Female",
    "FEMALE" : "Female", 
    "f" : "Female",
    "F" : "Female"
})

age_to_grade = {
    8 : "Grade 2",
    9 : "Grade 3",
    10 : "Grade 4",
    11 : "Grade 5",
    12 : "Grade 6",
    13 : "Grade 7",
    14 : "Grade 8",
    15 : "Grade 9", 
    16 : "Grade 10",
    17 : "Grade 11" 
}

students_df["grade"] = np.where(students_df["age"] <= 7, "Grade 1", students_df["grade"])

students_df["grade"] = np.where(students_df["age"] > 17, "Grade 12", students_df["grade"])

students_df["grade"] = students_df["age"].map(age_to_grade).fillna(students_df["grade"])

students_df["age_num"] = students_df["age"]
students_df = students_df.sort_values("age_num")
students_df = students_df.drop(columns = "age_num")
students_df["age"] = students_df["age"].abs()
students_df = students_df[-students_df["age"].isin([0, 150])]

students_df.head(3)

students_df.to_excel("Datasets/students_clean.xlsx", index = False)


with pd.ExcelWriter("Datasets/students_clean.xlsx", engine = "openpyxl") as writer: 
    students_df.to_excel(writer, index=False, sheet_name="students")
    ws = writer.sheets["students"]
    yellow = PatternFill(start_color = "FFFF00", end_color = "FFFF00", fill_type = "solid")
    red = PatternFill(start_color = "FF0000", end_color = "FF0000", fill_type = "solid")

    n_cols = len(students_df.columns)
    gpa_col = students_df.columns.get_loc("gpa")
    attendance_col_idx = students_df.columns.get_loc("attendance_rate")
    
    for row_idx, (_, row) in enumerate(students_df.iterrows(), start = 2):
        gpa = row["gpa"]
        attendance = row["attendance_rate"]

        if pd.isna(attendance):
            fill = red
            
        elif pd.notna(gpa) and gpa < 2:
            fill = yellow

        else:
            fill = None

        if fill:
            for col in range(1, n_cols + 1):
                ws.cell(row = row_idx, column = col).fill = fill

85