# Cleaning Data

In [1]:
import pandas as pd

In [20]:
df = pd.read_excel("Datasets/signup.xlsx")
df

     name   age        email signup_date
0   Alice  29.0  a@gmail.com  2024-01-02
1     Bob   NaN  b@gmail.com  2024-01-03
2  Carlos  41.0          NaN  2024-01-05
3     NaN  35.0  b@gmail.com  2024-01-06
4     NaN   NaN          NaN         NaT
5    John  21.0  j@gmail.com  2024-01-08
6   Alice  29.0  a@gmail.com  2024-01-02
7  Carlos  41.0          NaN  2024-01-05

<h2 style = "color:#4fd4ff" >Detecting Missing Values</h2>

Before you can fix missing data, you need to find it. <br>
Pandas represents a missing value as NaN (Not a Number). <br>
isnan() returns a same-shaped DataFrame of True/False. <br>
Returns True whenever a cell is missing.

In [5]:
df.isna()

    name    age  email  signup_date
0  False  False  False        False
1  False   True  False         True
2  False  False   True        False
3   True  False   True        False

Knowing that missing values exist is step 1. <br>
Knowing exactly how many, and in which columns, is what turns that into a plan. <br>
Chaining .sum() onto .isna() returns the count of missing values in each column.

In [17]:
df.isna().sum()

name           1
age            1
email          2
signup_date    1
dtype: int64

In [18]:
(df.isna().sum()/len(df) * 100).sort_values(ascending = False) # Percentage missing per column

email          50.0
name           25.0
age            25.0
signup_date    25.0
dtype: float64

In [21]:
df.isna().sum().sum() # Total missing cells in the entire DataFrame

np.int64(5)

In [22]:
df.info() # shows non-null count per column which is a mirror image of this command df.isna().sum()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         3 non-null      str
 1   age          3 non-null      float64
 2   email        2 non-null      str
 3   signup_date  3 non-null      datetime64[us]
dtypes: datetime64[us](1), float64(1), str(2)
memory usage: 260.0 bytes

<h2 style = "color:#4fd4ff" >Dropping Rows or Columns - dropna()</h2>

In [23]:
df.dropna() # Drops any row with at least one missing value

    name   age        email signup_date
0  Alice  29.0  a@gmail.com  2024-01-02

In [8]:
df.dropna(axis = 1) # Drops any column with a missing value instead of rows

  signup_date
0  2024-01-02
1  2024-01-03
2  2024-01-05
3  2024-01-06

In [13]:
df.dropna(how = "all") # Only drops a row if all its values are missing

     name   age        email signup_date
0   Alice  29.0  a@gmail.com  2024-01-02
1     Bob   NaN  b@gmail.com  2024-01-03
2  Carlos  41.0          NaN  2024-01-05
3     NaN  35.0          NaN  2024-01-06
5    John  21.0  j@gmail.com  2024-01-08

In [18]:
df.dropna(subset = ["name", "email"]) # Only considers missing values in specific columns

    name   age        email signup_date
0  Alice  29.0  a@gmail.com  2024-01-02
1    Bob   NaN  b@gmail.com  2024-01-03
5   John  21.0  j@gmail.com  2024-01-08

<h2 style = "color:#4fd4ff" >Duplicate Rows</h2>

Data collected from multiple sources - for example a form resumbited, 2 systems  merged, a scrapper run twice, almost always produces duplicate rows.<br>
.duplicated() flags them <br>
.drop_duplicates() removes them

In [5]:
#df = pd.read_excel("Datasets/kids_records.xlsx")
#df

In [11]:
df.isna().sum()

name           2
age            2
email          4
signup_date    1
dtype: int64

In [12]:
(df.isna().sum()/len(df) * 100).sort_values(ascending = False)

email          50.0
name           25.0
age            25.0
signup_date    12.5
dtype: float64

In [26]:
df = df.dropna(how = "all")

In [15]:
df.dropna(subset = ["name"])

     name   age        email signup_date
0   Alice  29.0  a@gmail.com  2024-01-02
1     Bob   NaN  b@gmail.com  2024-01-03
2  Carlos  41.0          NaN  2024-01-05
5    John  21.0  j@gmail.com  2024-01-08
6   Alice  29.0  a@gmail.com  2024-01-02
7  Carlos  41.0          NaN  2024-01-05

In [22]:
df.duplicated().sum()

np.int64(2)

In [23]:
df.drop_duplicates()

     name   age        email signup_date
0   Alice  29.0  a@gmail.com  2024-01-02
1     Bob   NaN  b@gmail.com  2024-01-03
2  Carlos  41.0          NaN  2024-01-05
3     NaN  35.0  b@gmail.com  2024-01-06
4     NaN   NaN          NaN         NaT
5    John  21.0  j@gmail.com  2024-01-08

In [29]:
dup_emails = df[df.duplicated(subset = ["email"], keep = False)].sort_values("email")
print(dup_emails)

     name   age        email signup_date
0   Alice  29.0  a@gmail.com  2024-01-02
6   Alice  29.0  a@gmail.com  2024-01-02
1     Bob   NaN  b@gmail.com  2024-01-03
3     NaN  35.0  b@gmail.com  2024-01-06
2  Carlos  41.0          NaN  2024-01-05
7  Carlos  41.0          NaN  2024-01-05

In [33]:
students_df = pd.read_excel("Datasets/school_kids_100.xlsx")
students_df

,student_id,first_name,last_name,gender,age,grade,email,phone_number,enrollment_date,gpa,city,guardian_name,attendance_rate
0,STU01919,Amanda,Grimes,FEMALE,NaN,Grade 1,amanda.grimes785@outlook.com,(95) 8857227,08-31-2019,3.21,Mongu,Mary Grimes,78.2
1,STU02745,Thomas,Wise,M,11.0,Grade 2,thomas_wise@gmail.com,260970116159,2023/07/01,2.45,Ndola,Michelle Wise,83.3
2,STU02843,Christopher,Brown,Male,6.0,Grade 9,christopher_brown@gmail.com,0962209692,27 Mar 2023,1.30,CHIPATA,Vanessa Brown,70.3
3,STU00654,Sara,Barnes,F,18.0,Grade 4,sara.barnes700@outlook.com,+260-97-1390306,13 Dec 2018,2.23,Chingola,William Barnes,96.7
4,STU03253,Erin,Williams,FEMALE,12.0,Grade 7,erinw52@school.edu.zm,260959255370,2023-09-29,3.05,mansa,Brian Williams,60.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,STU03356,Christopher,Webb,M,7.0,Grade 1,christopher.webb735@outlook.com,0975718099,27/01/2020,3.25,chingola,Alexis Webb,NaN
101,STU04713,Kathryn,Shields,F,7.0,Grade 12,kathryns57@school.edu.zm,+260-97-2662290,04/09/2020,2.83,Ndola,Wesley Shields,60.9
102,STU00066,Catherine,Lara,F,11.0,Grade 10,catherine.lara811@school.edu.zm,+260-97-7815076,2022/01/28,3.04,NDOLA,Jose Lara,65.0
103,STU01689,Jeremiah,Lawson,Female,-5.0,Grade 1,jeremiahl40@gmail.com,(97) 5072407,2018-05-26,3.65,Lusaka,Christina Lawson,62.1
104,STU01032,Loretta,Foster,M,18.0,Grade 3,loretta_foster@gmail.com,260974160580,10-23-2023,1.81,Solwezi,Juan Foster,99.7

In [36]:
students_df = students_df.dropna(how = "all")

In [39]:
students_df.duplicated().sum()

students_df = students_df.drop_duplicates()

In [40]:
students_df.duplicated().sum()

np.int64(0)

In [43]:
students_df = students_df.dropna(subset = ["student_id"])
students_df

,student_id,first_name,last_name,gender,age,grade,email,phone_number,enrollment_date,gpa,city,guardian_name,attendance_rate
0,STU01919,Amanda,Grimes,FEMALE,NaN,Grade 1,amanda.grimes785@outlook.com,(95) 8857227,08-31-2019,3.21,Mongu,Mary Grimes,78.2
1,STU02745,Thomas,Wise,M,11.0,Grade 2,thomas_wise@gmail.com,260970116159,2023/07/01,2.45,Ndola,Michelle Wise,83.3
2,STU02843,Christopher,Brown,Male,6.0,Grade 9,christopher_brown@gmail.com,0962209692,27 Mar 2023,1.30,CHIPATA,Vanessa Brown,70.3
3,STU00654,Sara,Barnes,F,18.0,Grade 4,sara.barnes700@outlook.com,+260-97-1390306,13 Dec 2018,2.23,Chingola,William Barnes,96.7
4,STU03253,Erin,Williams,FEMALE,12.0,Grade 7,erinw52@school.edu.zm,260959255370,2023-09-29,3.05,mansa,Brian Williams,60.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,STU00561,Marilyn,Becker,female,6.0,Grade 10,marilyn_becker@outlook.com,+260-95-9250481,NaN,3.96,kabwe,NaN,96.7
95,STU02632,Mark,Berry,MALE,10.0,Grade 3,markb13@yahoo.com,0958362080,31/07/2024,4.00,ndola,Christian Berry,65.1
96,STU01292,Jeffrey,Romero,FEMALE,10.0,Grade 2,jeffrey.romero723@outlook.com,260976857486,10-01-2020,3.32,CHIPATA,Sheryl Romero,92.4
97,STU02335,Zachary,Cook,m,10.0,Grade 11,zachary_cook@outlook.com,(97) 5757898,05 Mar 2021,2.33,NaN,Heidi Cook,89.2
98,STU01296,Richard,Reid,m,15.0,Grade 10,richardr35@gmail.com,0953489781,26 Jan 2024,3.16,LIVINGSTONE,Mikayla Reid,62.5

In [44]:
print(len(students_df))

88

In [45]:
students_df["gender"] = students_df["gender"].str.strip().str.upper().map({
    "m" : "Male",
    "M" : "Male",
    "MALE" : "Male",
    "male" : "Male",
    "female" : "Female",
    "FEMALE" : "Female", 
    "f" : "Female",
    "F" : "Female"
})

In [46]:
students_df

,student_id,first_name,last_name,gender,age,grade,email,phone_number,enrollment_date,gpa,city,guardian_name,attendance_rate
0,STU01919,Amanda,Grimes,Female,NaN,Grade 1,amanda.grimes785@outlook.com,(95) 8857227,08-31-2019,3.21,Mongu,Mary Grimes,78.2
1,STU02745,Thomas,Wise,Male,11.0,Grade 2,thomas_wise@gmail.com,260970116159,2023/07/01,2.45,Ndola,Michelle Wise,83.3
2,STU02843,Christopher,Brown,Male,6.0,Grade 9,christopher_brown@gmail.com,0962209692,27 Mar 2023,1.30,CHIPATA,Vanessa Brown,70.3
3,STU00654,Sara,Barnes,Female,18.0,Grade 4,sara.barnes700@outlook.com,+260-97-1390306,13 Dec 2018,2.23,Chingola,William Barnes,96.7
4,STU03253,Erin,Williams,Female,12.0,Grade 7,erinw52@school.edu.zm,260959255370,2023-09-29,3.05,mansa,Brian Williams,60.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,STU00561,Marilyn,Becker,Female,6.0,Grade 10,marilyn_becker@outlook.com,+260-95-9250481,NaN,3.96,kabwe,NaN,96.7
95,STU02632,Mark,Berry,Male,10.0,Grade 3,markb13@yahoo.com,0958362080,31/07/2024,4.00,ndola,Christian Berry,65.1
96,STU01292,Jeffrey,Romero,Female,10.0,Grade 2,jeffrey.romero723@outlook.com,260976857486,10-01-2020,3.32,CHIPATA,Sheryl Romero,92.4
97,STU02335,Zachary,Cook,Male,10.0,Grade 11,zachary_cook@outlook.com,(97) 5757898,05 Mar 2021,2.33,NaN,Heidi Cook,89.2
98,STU01296,Richard,Reid,Male,15.0,Grade 10,richardr35@gmail.com,0953489781,26 Jan 2024,3.16,LIVINGSTONE,Mikayla Reid,62.5

In [47]:
students_df.to_excel("Datasets/students_clean.xlsx", index = False)